swagger: 2.0
info:
  title: IndianaLearns API
  description: We believe important conversations about the future of our educational system can be enhanced by utilizing data freely available to the citizens of Indiana. We've organized it here.
  version: "1.0.0"
# the domain of the service
host: indianalearns.info
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /api/v1
produces:
  - application/json
paths:
  /corporations:
    get:
      summary: Corporation Directory
      description: Directory of all known school districts/corporations
      parameters:
        - name: id
          in: query
          description: School corporation ID as assigned by State of Indiana
          required: false
          type: number
        - name: name
          in: query
          description: School corporation name as registered in the State of Indiana
          required: false
          type: string         
        - name: address
          in: query
          description: Street address of corporation headquarters
          required: false
          type: string
        - name: city
          in: query
          description: City of corporation headquarters
          required: false
          type: string
        - name: zip
          in: query
          description: ZIP of corporation headquarters
          required: false
          type: number
        - name: grade_span
          in: query
          description: A span of grades the corporation covers, where KG = Kindergarten, PK = Pre-Kindergarten, and SP & ED = Special Education
          required: false
          type: string
        - name: phone
          in: query
          description: Phone number of corporation headquarters
          required: false
          type: string
        - name: fax
          in: query
          description: Fax of corporation headquarters
          required: false
          type: string
        - name: superintendent_name
          in: query
          description: The name of the superintendent of the corporation
          required: false
          type: string
        - name: superintendent_email
          in: query
          description: The email of the superintendent of the corporation
          required: false
          type: string
        - name: gis_url
          in: query
          description: The GIS URL for the maps.indiana.edu entry related to the corporation
          required: false
          type: string
        - name: limit
          in: query
          description: Maximum number of results to return.
          required: false
          type: integer

      tags: 
        - Corporations
      responses:  
        "200":
          description: An array of Corporations
          schema:
            $ref: Corporations
        "404":
          description: The requested resource could not be found.
        default:
          description: What on earth have you done?
definitions:
  Corporation:
    properties:
      id:
        type: number
        description: School corporation ID as assigned by State of Indiana.
      name:
        type: string
        description: School corporation name as registered in the State of Indiana.
      address:
        type: string
        description: Street address of corporation headquarters.
      city:
        type: string
        description: City of corporation headquarters.
      zip:
        type: number
        description: ZIP of corporation headquarters.
      grade_span:
        type: string
        description: A span of grades the corporation covers, where KG = Kindergarten, PK = Pre-Kindergarten, and SP & ED = Special Education.
      phone:
        type: string
        description: Phone number of corporation headquarters.
      fax:
        type: string
        description: Fax of corporation headquarters.
      superintendent_name:
        type: string
        description: The name of the superintendent of the corporation.
      superintendent_email:
        type: string
        description: The email of the superintendent of the corporation.        
      gis_url:
        type: string
        description: The GIS URL for the maps.indiana.edu entry related to the corporation.        
  Corporations:
    type: array
    items:
      $ref: Corporation